package cloud.xcan.angus.extension.sms.api;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

/**
 * SMS information.
 *
 * @author XiaoLong Liu
 */
public class Sms implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * SMS signature.
   */
  private String sign;
  /**
   * Receive SMS mobile.
   */
  private List<String> mobiles;
  /**
   * SMS template code generated by SMS service provider.
   */
  private String templateCode;
  /**
   * Parameters and corresponding values in the template.
   */
  private Map<String, String> templateParams;

  public Sms() {
  }

  public Sms(String sign, List<String> mobiles, String templateCode,
      Map<String, String> templateParams) {
    this.sign = sign;
    this.mobiles = mobiles;
    this.templateCode = templateCode;
    this.templateParams = templateParams;
  }

  public String getTemplateCode() {
    return templateCode;
  }

  public Sms setTemplateCode(String templateCode) {
    this.templateCode = templateCode;
    return this;
  }

  public Map<String, String> getTemplateParams() {
    return templateParams;
  }

  public Sms setTemplateParams(Map<String, String> templateParams) {
    this.templateParams = templateParams;
    return this;
  }

  public String getSign() {
    return sign;
  }

  public Sms setSign(String sign) {
    this.sign = sign;
    return this;
  }

  public List<String> getMobiles() {
    return mobiles;
  }

  public Sms setMobiles(List<String> mobiles) {
    this.mobiles = mobiles;
    return this;
  }
}
