import { GM, PUB_GM , ESS} from '@xcan-angus/tools';

import Tenant from '@/api/Tenant';
import User from '@/api/User';
import UserDirectory from '@/api/UserDirectory';
import Dept from '@/api/Dept';
import Group from '@/api/Group';
import OrgTag from '@/api/OrgTag';
import App from '@/api/App';
import Auth from '@/api/Auth';
import UserToken from '@/api/UserToken';
import SystemToken from '@/api/SystemToken';
import Service from '@/api/Service';
import Social from '@/api/Social';
import Online from '@/api/Online';
import Actuator from '@/api/Actuator';
import Email from '@/api/Email';
import Event from '@/api/Event';
import SystemLog from '@/api/SystemLog';
import UserLog from '@/api/UserLog';
import Message from '@/api/Message';
import Notice from '@/api/Notice';
import Setting from '@/api/Setting';
import Sms from '@/api/Sms';
import Edition from '@/api/Edition';
import CloudStore from '@/api/CloudStore';
import License from '@/api/License';
import PrivStore from '@/api/PrivStore';
import PrivLicense from '@/api/PrivLicense';
import Signin from '@/api/Signin';
import PubProxy from '@/api/PubProxy';

export const tenant = new Tenant(GM);
export const user = new User(GM);
export const userDirectory = new UserDirectory(GM);
export const dept = new Dept(GM);
export const group = new Group(GM);
export const orgTag = new OrgTag(GM);
export const app = new App(GM);
export const auth = new Auth(GM);
export const userToken = new UserToken(GM);
export const systemToken = new SystemToken(GM);
export const service = new Service(GM);
export const social = new Social(GM);
export const online = new Online(GM);
export const actuator = new Actuator();
export const email = new Email(GM);
export const event = new Event(GM);
export const systemLog = new SystemLog(GM);
export const userLog = new UserLog(GM);
export const message = new Message(GM);
export const notice = new Notice(GM);
export const setting = new Setting(GM);
export const sms = new Sms(GM);
export const edition = new Edition(ESS);
export const store = new CloudStore(ESS);
export const privStore = new PrivStore(GM);
export const license = new License(ESS);
export const privLicense = new PrivLicense(GM);
export const login = new Signin(PUB_GM);
export const pubProxy = new PubProxy(PUB_GM);
